#!/usr/bin/python
import socket
from termcolor import colored
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
socket.setdefaulttimeout(2)

host = raw_input("[*]Enter the host:")


def portscanner(port):
	if sock.connect_ex((host,port)):
		print (colored("[!!]Port %d is closed" %(port),'red'))
	else:
		print (colored("port %d is opened" %(port),'green'))

for port in  range(1,100):
	portscanner(port)
